### PR TITLE
[MINSTALL-201] Don't zip pom artifacts

### PR DESCRIPTION
**Pull request by kohlschuetter**
3.1.2 introduced a regression that may cause pom artifacts to be installed as zip files (with a pom suffix) instead of raw .pom files.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MINSTALL) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MINSTALL-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MINSTALL-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by kohlschuetter** [comment]
(PR based off 3.1.2)

**Review by elharo — COMMENTED** [review]
test?

**Comment by kohlschuetter** [comment]
@elharo As a mere user of this plugin, I thought reporting and putting out a fix for this was enough. Do you mind adding the test code the way you envision it? Cheers!

**Comment by elharo** [comment]
We can take a bug report. Fixes without tests are not reliable.

**Comment by kohlschuetter** [comment]
@elharo You got a bug report for a blocking bug/regression sitting around for a month, and now you're closing it because nondescript tests are lacking. Way to go...

**Comment by elharo** [comment]
I'm not closing the bug. I'm closing a bad fix.

**Comment by kohlschuetter** [comment]
@elharo OK, fine with me as long as you fix the bug :) Thanks

**Comment by jira-importer** [comment]
Resolve #315

**Pull request closed without merging**
