### PR TITLE
MINSTALL-153 Remove the remnants of the updateReleaseInfo parameter

### PR DESCRIPTION
**Pull request by vovkss**
The `updateReleaseInfo` parameter has been removed:

https://issues.apache.org/jira/browse/MINSTALL-149

But the plugin's site still has an "Examples" section for this parameter.

This pull request removes the remnants of the parameter.

### CODE REVIEW

**Comment by khmarbaise** [comment]
Can you please create a new JIRA issue for that...and rebase and update the commit message in your PR...would be great...

**Comment by vovkss** [comment]
New task: https://issues.apache.org/jira/browse/MINSTALL-149
Updated the pull request's title.

**Comment by jira-importer** [comment]
Resolve #246

**Comment by jira-importer** [comment]
Resolve #277

**Pull request closed without merging**
